export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504
}
export enum HttpMessage {
  OK = 'OK',
  CREATED = 'CREATED',
  NO_CONTENT = 'NO CONTENT',
  BAD_REQUEST = 'BAD REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE UNAVAILABLE',
  GATEWAY_TIMEOUT = 'GATEWAY TIMEOUT'
}
export enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER'
}